# Default initial positions for gcr5_910's ros2_control fake system

initial_positions:
  arm_1_joint_1: 0
  arm_1_joint_2: 0
  arm_1_joint_3: 0
  arm_1_joint_4: 0
  arm_1_joint_5: 0
  arm_1_joint_6: 0