arm_1_controller:
  ros__parameters:
    action_monitor_rate: 62.5
    allow_integration_in_goal_trajectories: true
    allow_partial_joints_goal: false
    command_interfaces:
    - position
    constraints:
      arm_1_joint_1:
        goal: 0.05
        trajectory: 0.13
      arm_1_joint_2:
        goal: 0.05
        trajectory: 0.13
      arm_1_joint_3:
        goal: 0.05
        trajectory: 0.13
      arm_1_joint_4:
        goal: 0.05
        trajectory: 0.13
      arm_1_joint_5:
        goal: 0.05
        trajectory: 0.13
      arm_1_joint_6:
        goal: 0.05
        trajectory: 0.13
      goal_time: 0.69
      stopped_velocity_tolerance: 0.01
    joints:
    - arm_1_joint_1
    - arm_1_joint_2
    - arm_1_joint_3
    - arm_1_joint_4
    - arm_1_joint_5
    - arm_1_joint_6
    open_loop_control: false
    state_interfaces:
    - position
    - velocity
controller_manager:
  ros__parameters:
    arm_1_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    update_rate: 250
joint_state_broadcaster:
  ros__parameters:
    joints:
    - arm_1_joint_1
    - arm_1_joint_2
    - arm_1_joint_3
    - arm_1_joint_4
    - arm_1_joint_5
    - arm_1_joint_6
