# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_1_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_1_controller:
  ros__parameters:
    joints:
      - arm_1_joint_1
      - arm_1_joint_2
      - arm_1_joint_3
      - arm_1_joint_4
      - arm_1_joint_5
      - arm_1_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      arm_1_joint_1:
        trajectory: 0.1
        goal: 0.05
      arm_1_joint_2:
        trajectory: 0.1
        goal: 0.05
      arm_1_joint_3:
        trajectory: 0.1
        goal: 0.05
      arm_1_joint_4:
        trajectory: 0.1
        goal: 0.05
      arm_1_joint_5:
        trajectory: 0.1
        goal: 0.05
      arm_1_joint_6:
        trajectory: 0.1
        goal: 0.05

joint_state_broadcaster:
  ros__parameters:
    joints:
      - arm_1_joint_1
      - arm_1_joint_2
      - arm_1_joint_3
      - arm_1_joint_4
      - arm_1_joint_5
      - arm_1_joint_6