# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_1_controller
    - arm_2_controller
    - arms_controller

  arm_1_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_1_joint_1
      - arm_1_joint_2
      - arm_1_joint_3
      - arm_1_joint_4
      - arm_1_joint_5
      - arm_1_joint_6
    action_ns: follow_joint_trajectory
    default: true
  arm_2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_2_joint_1
      - arm_2_joint_2
      - arm_2_joint_3
      - arm_2_joint_4
      - arm_2_joint_5
      - arm_2_joint_6
    action_ns: follow_joint_trajectory
    default: true
  arms_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_1_joint_1
      - arm_1_joint_2
      - arm_1_joint_3
      - arm_1_joint_4
      - arm_1_joint_5
      - arm_1_joint_6
      - arm_2_joint_1
      - arm_2_joint_2
      - arm_2_joint_3
      - arm_2_joint_4
      - arm_2_joint_5
      - arm_2_joint_6
    action_ns: follow_joint_trajectory
    default: true
