# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_1_controller:
  ros__parameters:
    joints:
      - arm_1_joint_1
      - arm_1_joint_2
      - arm_1_joint_3
      - arm_1_joint_4
      - arm_1_joint_5
      - arm_1_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_2_controller:
  ros__parameters:
    joints:
      - arm_2_joint_1
      - arm_2_joint_2
      - arm_2_joint_3
      - arm_2_joint_4
      - arm_2_joint_5
      - arm_2_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arms_controller:
  ros__parameters:
    joints:
      - arm_1_joint_1
      - arm_1_joint_2
      - arm_1_joint_3
      - arm_1_joint_4
      - arm_1_joint_5
      - arm_1_joint_6
      - arm_2_joint_1
      - arm_2_joint_2
      - arm_2_joint_3
      - arm_2_joint_4
      - arm_2_joint_5
      - arm_2_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity